ERROR 2014-11-26 11:15:53,013 service 28735 140506855802592 execute command error the input 
 db-stest-zk0.db01.baidu.com:3000/sandbox/tera/nmg-lb(
Traceback (most recent call last):
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/service.py", line 83, in _execute
    status, _ , error = self.shell_helper.run_with_retuncode(command)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/frame/shell/command.py", line 36, in run_with_retuncode
    output, errout = p.communicate()
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 754, in communicate
    return self._communicate(input)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 1312, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 1366, in _communicate_with_poll
    ready = poller.poll()
  File "/home/users/wangtaize/.jumbo/lib/python2.7/site-packages/gunicorn/workers/base.py", line 154, in handle_abort
    sys.exit(1)
SystemExit: 1
ERROR 2014-11-26 11:22:43,007 service 15365 140588040713952 execute command error the input 
 db-stest-zk0.db01.baidu.com:3000/sandbox/tera/nmg-lb(
Traceback (most recent call last):
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/service.py", line 83, in _execute
    status, _ , error = self.shell_helper.run_with_retuncode(command)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/frame/shell/command.py", line 36, in run_with_retuncode
    output, errout = p.communicate()
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 754, in communicate
    return self._communicate(input)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 1312, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 1366, in _communicate_with_poll
    ready = poller.poll()
  File "/home/users/wangtaize/.jumbo/lib/python2.7/site-packages/gunicorn/workers/base.py", line 154, in handle_abort
    sys.exit(1)
SystemExit: 1
ERROR 2014-11-26 11:23:10,027 service 15364 140588040713952 execute command error the input 
 db-stest-zk0.db01.baidu.com:3000/sandbox/tera/nmg-lb(
Traceback (most recent call last):
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/service.py", line 83, in _execute
    status, _ , error = self.shell_helper.run_with_retuncode(command)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/frame/shell/command.py", line 36, in run_with_retuncode
    output, errout = p.communicate()
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 754, in communicate
    return self._communicate(input)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 1312, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 1366, in _communicate_with_poll
    ready = poller.poll()
  File "/home/users/wangtaize/.jumbo/lib/python2.7/site-packages/gunicorn/workers/base.py", line 154, in handle_abort
    sys.exit(1)
SystemExit: 1
WARNING 2014-11-26 11:23:10,464 base 17168 140588040713952 Not Found: /favicon.ico
ERROR 2014-11-26 11:23:58,019 service 17604 140588040713952 execute command error the input 
 db-stest-zk0.db01.baidu.com:3000/sandbox/tera/nmg-lb(
Traceback (most recent call last):
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/service.py", line 83, in _execute
    status, _ , error = self.shell_helper.run_with_retuncode(command)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/frame/shell/command.py", line 36, in run_with_retuncode
    output, errout = p.communicate()
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 754, in communicate
    return self._communicate(input)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 1312, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 1366, in _communicate_with_poll
    ready = poller.poll()
  File "/home/users/wangtaize/.jumbo/lib/python2.7/site-packages/gunicorn/workers/base.py", line 154, in handle_abort
    sys.exit(1)
SystemExit: 1
ERROR 2014-11-26 11:26:46,026 service 21158 140588040713952 execute command error the input 
 db-stest-zk0.db01.baidu.com:3000/sandbox/tera/nmg-lb(
Traceback (most recent call last):
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/service.py", line 83, in _execute
    status, _ , error = self.shell_helper.run_with_retuncode(command)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/frame/shell/command.py", line 36, in run_with_retuncode
    output, errout = p.communicate()
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 754, in communicate
    return self._communicate(input)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 1312, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 1366, in _communicate_with_poll
    ready = poller.poll()
  File "/home/users/wangtaize/.jumbo/lib/python2.7/site-packages/gunicorn/workers/base.py", line 154, in handle_abort
    sys.exit(1)
SystemExit: 1
ERROR 2014-11-26 11:26:57,011 service 17168 140588040713952 execute command error the input 
 db-stest-zk0.db01.baidu.com:3000/sandbox/tera/nmg-lb(
Traceback (most recent call last):
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/service.py", line 83, in _execute
    status, _ , error = self.shell_helper.run_with_retuncode(command)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/frame/shell/command.py", line 36, in run_with_retuncode
    output, errout = p.communicate()
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 754, in communicate
    return self._communicate(input)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 1312, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 1366, in _communicate_with_poll
    ready = poller.poll()
  File "/home/users/wangtaize/.jumbo/lib/python2.7/site-packages/gunicorn/workers/base.py", line 154, in handle_abort
    sys.exit(1)
SystemExit: 1
ERROR 2014-11-26 11:27:16,019 service 26544 140588040713952 execute command error the input 
 db-stest-zk0.db01.baidu.com:3000/sandbox/tera/nmg-lb(
Traceback (most recent call last):
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/service.py", line 83, in _execute
    status, _ , error = self.shell_helper.run_with_retuncode(command)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/frame/shell/command.py", line 36, in run_with_retuncode
    output, errout = p.communicate()
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 754, in communicate
    return self._communicate(input)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 1312, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 1366, in _communicate_with_poll
    ready = poller.poll()
  File "/home/users/wangtaize/.jumbo/lib/python2.7/site-packages/gunicorn/workers/base.py", line 154, in handle_abort
    sys.exit(1)
SystemExit: 1
ERROR 2014-11-26 11:27:27,011 service 26746 140588040713952 execute command error the input 
 db-stest-zk0.db01.baidu.com:3000/sandbox/tera/nmg-lb(
Traceback (most recent call last):
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/service.py", line 83, in _execute
    status, _ , error = self.shell_helper.run_with_retuncode(command)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/frame/shell/command.py", line 36, in run_with_retuncode
    output, errout = p.communicate()
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 754, in communicate
    return self._communicate(input)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 1312, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 1366, in _communicate_with_poll
    ready = poller.poll()
  File "/home/users/wangtaize/.jumbo/lib/python2.7/site-packages/gunicorn/workers/base.py", line 154, in handle_abort
    sys.exit(1)
SystemExit: 1
ERROR 2014-11-26 11:27:40,580 base 28628 140588040713952 Internal Server Error: /monitor/statLine
Traceback (most recent call last):
  File "/home/users/wangtaize/.jumbo/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/decorator.py", line 24, in node_required_wrapper
    return func(request, *args, **kwds)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/views.py", line 88, in render_node_stat_line
    node_stat_dict_stream = dicts_to_prop_stream(node_stat_dict['stat'])
KeyError: 'stat'
ERROR 2014-11-26 11:27:50,023 service 28383 140588040713952 execute command error the input 
 db-stest-zk0.db01.baidu.com:3000/sandbox/tera/nmg-lb(
Traceback (most recent call last):
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/service.py", line 83, in _execute
    status, _ , error = self.shell_helper.run_with_retuncode(command)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/frame/shell/command.py", line 36, in run_with_retuncode
    output, errout = p.communicate()
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 754, in communicate
    return self._communicate(input)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 1312, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 1366, in _communicate_with_poll
    ready = poller.poll()
  File "/home/users/wangtaize/.jumbo/lib/python2.7/site-packages/gunicorn/workers/base.py", line 154, in handle_abort
    sys.exit(1)
SystemExit: 1
ERROR 2014-11-26 11:28:22,695 base 29333 140588040713952 Internal Server Error: /monitor/statLine
Traceback (most recent call last):
  File "/home/users/wangtaize/.jumbo/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/decorator.py", line 24, in node_required_wrapper
    return func(request, *args, **kwds)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/views.py", line 88, in render_node_stat_line
    node_stat_dict_stream = dicts_to_prop_stream(node_stat_dict['stat'])
KeyError: 'stat'
ERROR 2014-11-26 11:28:28,861 base 29333 140588040713952 Internal Server Error: /monitor/statLine
Traceback (most recent call last):
  File "/home/users/wangtaize/.jumbo/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/decorator.py", line 24, in node_required_wrapper
    return func(request, *args, **kwds)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/views.py", line 88, in render_node_stat_line
    node_stat_dict_stream = dicts_to_prop_stream(node_stat_dict['stat'])
KeyError: 'stat'
ERROR 2014-11-26 11:28:45,020 service 28628 140588040713952 execute command error the input 
 db-stest-zk0.db01.baidu.com:3000/sandbox/tera/nmg-lb(
Traceback (most recent call last):
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/service.py", line 83, in _execute
    status, _ , error = self.shell_helper.run_with_retuncode(command)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/frame/shell/command.py", line 36, in run_with_retuncode
    output, errout = p.communicate()
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 754, in communicate
    return self._communicate(input)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 1312, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 1366, in _communicate_with_poll
    ready = poller.poll()
  File "/home/users/wangtaize/.jumbo/lib/python2.7/site-packages/gunicorn/workers/base.py", line 154, in handle_abort
    sys.exit(1)
SystemExit: 1
ERROR 2014-11-26 11:31:27,389 base 5992 140458960053984 Internal Server Error: /monitor/statLine
Traceback (most recent call last):
  File "/home/users/wangtaize/.jumbo/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/decorator.py", line 24, in node_required_wrapper
    return func(request, *args, **kwds)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/views.py", line 89, in render_node_stat_line
    node_stat_dict_stream = dicts_to_prop_stream(node_stat_dict['stat'])
KeyError: 'stat'
ERROR 2014-11-26 11:54:01,007 service 28316 140106979546848 execute command error the input 
 db-stest-zk0.db01.baidu.com:3000/sandbox/tera/nmg-lb(
Traceback (most recent call last):
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/service.py", line 83, in _execute
    status, _ , error = self.shell_helper.run_with_retuncode(command)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/frame/shell/command.py", line 36, in run_with_retuncode
    output, errout = p.communicate()
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 754, in communicate
    return self._communicate(input)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 1312, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 1366, in _communicate_with_poll
    ready = poller.poll()
  File "/home/users/wangtaize/.jumbo/lib/python2.7/site-packages/gunicorn/workers/base.py", line 154, in handle_abort
    sys.exit(1)
SystemExit: 1
ERROR 2014-11-26 11:55:57,022 service 30812 140106979546848 execute command error the input 
 db-stest-zk0.db01.baidu.com:3000/sandbox/tera/nmg-lb(
Traceback (most recent call last):
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/service.py", line 83, in _execute
    status, _ , error = self.shell_helper.run_with_retuncode(command)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/frame/shell/command.py", line 36, in run_with_retuncode
    output, errout = p.communicate()
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 754, in communicate
    return self._communicate(input)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 1312, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 1366, in _communicate_with_poll
    ready = poller.poll()
  File "/home/users/wangtaize/.jumbo/lib/python2.7/site-packages/gunicorn/workers/base.py", line 154, in handle_abort
    sys.exit(1)
SystemExit: 1
ERROR 2014-11-26 11:56:15,018 service 28274 140106979546848 execute command error the input 
 db-stest-zk0.db01.baidu.com:3000/sandbox/tera/nmg-lb(
Traceback (most recent call last):
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/service.py", line 83, in _execute
    status, _ , error = self.shell_helper.run_with_retuncode(command)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/frame/shell/command.py", line 36, in run_with_retuncode
    output, errout = p.communicate()
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 754, in communicate
    return self._communicate(input)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 1312, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 1366, in _communicate_with_poll
    ready = poller.poll()
  File "/home/users/wangtaize/.jumbo/lib/python2.7/site-packages/gunicorn/workers/base.py", line 154, in handle_abort
    sys.exit(1)
SystemExit: 1
ERROR 2014-11-26 13:05:57,452 service 19463 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-130555.19586'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-130556.19586'!
E1126 13:05:56.376749 19586 tera/monitor/teramo_main.cc:94] min: 1416935155001319 max: 1416978355001319

ERROR 2014-11-26 13:06:06,292 service 19463 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-130604.19804'!

ERROR 2014-11-26 13:06:10,210 service 19462 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-130607.19868'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-130608.19868'!
E1126 13:06:08.926139 19868 tera/monitor/teramo_main.cc:94] min: 1416935167675614 max: 1416978367675614

ERROR 2014-11-26 13:06:23,032 service 19463 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-130621.21181'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-130622.21181'!
E1126 13:06:22.066453 21181 tera/monitor/teramo_main.cc:94] min: 1416935180837426 max: 1416978380837426

ERROR 2014-11-26 13:06:28,486 service 19462 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-130626.21326'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-130627.21326'!
E1126 13:06:27.704730 21326 tera/monitor/teramo_main.cc:94] min: 1416935186452436 max: 1416978386452436

ERROR 2014-11-26 13:06:34,801 service 19462 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-130630.21390'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-130631.21390'!
E1126 13:06:31.616329 21390 tera/monitor/teramo_main.cc:94] min: 1416935190180033 max: 1416978390180033

ERROR 2014-11-26 13:08:43,640 service 19463 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-130842.25845'!

ERROR 2014-11-26 13:09:39,922 service 19463 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-130938.27950'!

ERROR 2014-11-26 13:09:43,516 service 19463 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-130941.28117'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-130942.28117'!
E1126 13:09:42.484571 28117 tera/monitor/teramo_main.cc:94] min: 1416935381049102 max: 1416978581049102

ERROR 2014-11-26 13:09:48,583 service 19462 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-130946.28219'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-130947.28219'!
E1126 13:09:47.331367 28219 tera/monitor/teramo_main.cc:94] min: 1416935386197044 max: 1416978586197044

ERROR 2014-11-26 13:09:52,092 service 19463 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-130950.28285'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-130951.28285'!
E1126 13:09:51.204799 28285 tera/monitor/teramo_main.cc:94] min: 1416935390105453 max: 1416978590105453

ERROR 2014-11-26 13:09:59,312 service 19463 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-130957.28445'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-130958.28445'!
E1126 13:09:58.464871 28445 tera/monitor/teramo_main.cc:94] min: 1416935397364340 max: 1416978597364340

ERROR 2014-11-26 13:10:02,871 service 19462 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131001.28550'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131002.28550'!
E1126 13:10:02.037974 28550 tera/monitor/teramo_main.cc:94] min: 1416935400929971 max: 1416978600929971

WARNING 2014-11-26 13:10:07,590 base 19463 139938049193696 Not Found: /img/favicon.ico
ERROR 2014-11-26 13:10:09,562 service 19462 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131008.28716'!

ERROR 2014-11-26 13:10:12,821 service 19463 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131011.29565'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131011.29565'!
E1126 13:10:11.810828 29565 tera/monitor/teramo_main.cc:94] min: 1416935410693547 max: 1416978610693547

WARNING 2014-11-26 13:11:08,096 base 19463 139938049193696 Not Found: /favicon.ico
ERROR 2014-11-26 13:11:09,704 service 19462 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131108.31387'!

ERROR 2014-11-26 13:11:16,058 service 19462 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131114.32652'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131115.32652'!
E1126 13:11:15.030717 32652 tera/monitor/teramo_main.cc:94] min: 1416935473906006 max: 1416978673906006

ERROR 2014-11-26 13:11:31,345 service 19463 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131129.396'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131130.396'!
E1126 13:11:30.617164   396 tera/monitor/teramo_main.cc:94] min: 1416892260000000 max: 1416906000000000

ERROR 2014-11-26 13:11:40,790 service 19462 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131138.595'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131139.595'!
E1126 13:11:39.236867   595 tera/monitor/teramo_main.cc:94] min: 1416892260000000 max: 1416906000000000

ERROR 2014-11-26 13:11:44,495 service 19463 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131142.821'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131143.821'!
E1126 13:11:43.644351   821 tera/monitor/teramo_main.cc:94] min: 1416892260000000 max: 1416906000000000

ERROR 2014-11-26 13:11:47,866 service 19462 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131146.889'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131146.889'!
E1126 13:11:46.948878   889 tera/monitor/teramo_main.cc:94] min: 1416892260000000 max: 1416906000000000

ERROR 2014-11-26 13:11:55,974 service 19463 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131154.1059'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131154.1059'!
E1126 13:11:54.946377  1059 tera/monitor/teramo_main.cc:94] min: 1416892260000000 max: 1416906000000000

ERROR 2014-11-26 13:11:59,334 service 19462 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131157.1134'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131158.1134'!
E1126 13:11:58.565400  1134 tera/monitor/teramo_main.cc:94] min: 1416892260000000 max: 1416906000000000

ERROR 2014-11-26 13:12:03,071 service 19463 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131201.1230'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131202.1230'!
E1126 13:12:02.060889  1230 tera/monitor/teramo_main.cc:94] min: 1416892260000000 max: 1416906000000000

ERROR 2014-11-26 13:12:08,241 service 19463 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131207.1383'!

ERROR 2014-11-26 13:12:15,621 service 19462 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131213.2769'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131214.2769'!
E1126 13:12:14.671008  2769 tera/monitor/teramo_main.cc:94] min: 1416935533531922 max: 1416978733531922

ERROR 2014-11-26 13:12:26,754 service 19463 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131224.2944'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131225.2944'!
E1126 13:12:25.557540  2944 tera/monitor/teramo_main.cc:94] min: 1416935544452406 max: 1416978744452406

ERROR 2014-11-26 13:12:30,277 service 19462 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131228.3011'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131229.3011'!
E1126 13:12:29.557402  3011 tera/monitor/teramo_main.cc:94] min: 1416935548405197 max: 1416978748405197

ERROR 2014-11-26 13:12:33,386 service 19463 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131231.3129'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131232.3129'!
E1126 13:12:32.546012  3129 tera/monitor/teramo_main.cc:94] min: 1416935551428453 max: 1416978751428453

ERROR 2014-11-26 13:12:37,547 service 19463 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131235.3211'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131236.3211'!
E1126 13:12:36.744653  3211 tera/monitor/teramo_main.cc:94] min: 1416935555629634 max: 1416978755629634

ERROR 2014-11-26 13:12:41,503 service 19463 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131239.3264'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131240.3264'!
E1126 13:12:40.703447  3264 tera/monitor/teramo_main.cc:94] min: 1416935559588399 max: 1416978759588399

ERROR 2014-11-26 13:12:44,860 service 19462 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131243.3461'!

ERROR 2014-11-26 13:12:48,205 service 19462 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131247.3529'!

ERROR 2014-11-26 13:12:52,272 service 19462 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131249.3579'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131250.3579'!
E1126 13:12:50.532117  3579 tera/monitor/teramo_main.cc:94] min: 1416935569412677 max: 1416978769412677

ERROR 2014-11-26 13:13:14,918 service 19463 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131313.5172'!

ERROR 2014-11-26 13:13:20,028 service 19462 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131316.5241'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131317.5241'!
E1126 13:13:17.656527  5241 tera/monitor/teramo_main.cc:94] min: 1416935596276693 max: 1416978796276693

ERROR 2014-11-26 13:13:23,577 service 19463 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131321.5370'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131322.5370'!
E1126 13:13:22.763531  5370 tera/monitor/teramo_main.cc:94] min: 1416935601569669 max: 1416978801569669

ERROR 2014-11-26 13:13:27,640 service 19462 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131325.5438'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131326.5438'!
E1126 13:13:26.680495  5438 tera/monitor/teramo_main.cc:94] min: 1416935604929113 max: 1416978804929113

ERROR 2014-11-26 13:13:30,663 service 19463 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131328.5502'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131329.5502'!
E1126 13:13:29.858081  5502 tera/monitor/teramo_main.cc:94] min: 1416935608656984 max: 1416978808656984

ERROR 2014-11-26 13:13:34,124 service 19462 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131332.5630'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131333.5630'!
E1126 13:13:33.397708  5630 tera/monitor/teramo_main.cc:94] min: 1416935612306227 max: 1416978812306227

ERROR 2014-11-26 13:13:37,412 service 19463 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131335.5703'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131336.5703'!
E1126 13:13:36.574249  5703 tera/monitor/teramo_main.cc:94] min: 1416935615479836 max: 1416978815479836

ERROR 2014-11-26 13:13:41,980 service 19463 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131340.5846'!

ERROR 2014-11-26 13:13:49,226 service 19463 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131344.5965'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131345.5965'!
E1126 13:13:45.779835  5965 tera/monitor/teramo_main.cc:94] min: 1416935624410848 max: 1416978824410848

ERROR 2014-11-26 13:13:53,690 service 19462 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131351.6128'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131352.6128'!
E1126 13:13:52.522390  6128 tera/monitor/teramo_main.cc:94] min: 1416935631512640 max: 1416978831512640

ERROR 2014-11-26 13:13:57,395 service 19463 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131355.6198'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131356.6198'!
E1126 13:13:56.630623  6198 tera/monitor/teramo_main.cc:94] min: 1416935635182760 max: 1416978835182760

ERROR 2014-11-26 13:14:07,886 service 19462 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131406.6520'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131407.6520'!
E1126 13:14:07.106989  6520 tera/monitor/teramo_main.cc:94] min: 1416935645968112 max: 1416978845968112

ERROR 2014-11-26 13:14:11,230 service 19463 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131409.6608'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131410.6608'!
E1126 13:14:10.296268  6608 tera/monitor/teramo_main.cc:94] min: 1416935649199310 max: 1416978849199310

ERROR 2014-11-26 13:14:14,716 service 19462 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131412.8001'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131413.8001'!
E1126 13:14:13.783452  8001 tera/monitor/teramo_main.cc:94] min: 1416935652184694 max: 1416978852184694

ERROR 2014-11-26 13:14:18,396 service 19463 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131416.8071'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131417.8071'!
E1126 13:14:17.597955  8071 tera/monitor/teramo_main.cc:94] min: 1416935656484721 max: 1416978856484721

ERROR 2014-11-26 13:14:21,224 service 19462 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131419.8132'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131420.8132'!
E1126 13:14:20.435540  8132 tera/monitor/teramo_main.cc:94] min: 1416935659332239 max: 1416978859332239

ERROR 2014-11-26 13:14:25,057 service 19463 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131423.8248'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131424.8248'!
E1126 13:14:24.112745  8248 tera/monitor/teramo_main.cc:94] min: 1416935662823132 max: 1416978862823132

ERROR 2014-11-26 13:14:29,182 service 19462 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131427.8319'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131428.8319'!
E1126 13:14:28.013051  8319 tera/monitor/teramo_main.cc:94] min: 1416935666894582 max: 1416978866894582

ERROR 2014-11-26 13:14:54,591 service 19462 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131453.8819'!

ERROR 2014-11-26 13:14:57,411 service 19462 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131455.8879'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131456.8879'!
E1126 13:14:56.434744  8879 tera/monitor/teramo_main.cc:94] min: 1416935695229985 max: 1416978895229985

ERROR 2014-11-26 13:14:59,907 service 19462 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131458.8943'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131459.8943'!
E1126 13:14:59.152922  8943 tera/monitor/teramo_main.cc:94] min: 1416935698032389 max: 1416978898032389

WARNING 2014-11-26 13:15:00,096 base 19462 139938049193696 Not Found: /img/favicon.ico
ERROR 2014-11-26 13:15:00,125 service 19463 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131458.8961'!

ERROR 2014-11-26 13:15:02,219 service 19462 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131500.9076'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131501.9076'!
E1126 13:15:01.233625  9076 tera/monitor/teramo_main.cc:94] min: 1416935700102732 max: 1416978900102732

ERROR 2014-11-26 13:15:03,837 service 19463 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131502.9180'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131502.9180'!
E1126 13:15:02.878387  9180 tera/monitor/teramo_main.cc:94] min: 1416935701763976 max: 1416978901763976

ERROR 2014-11-26 13:15:23,586 service 19462 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131522.11491'!

ERROR 2014-11-26 13:15:26,925 service 19463 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131525.11577'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131526.11577'!
E1126 13:15:26.064963 11577 tera/monitor/teramo_main.cc:94] min: 1416935724726185 max: 1416978924726185

ERROR 2014-11-26 13:15:26,961 service 19462 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131524.11570'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131525.11570'!
E1126 13:15:25.699811 11570 tera/monitor/teramo_main.cc:94] min: 1416935724563162 max: 1416978924563162

ERROR 2014-11-26 13:15:30,976 service 19462 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131528.11677'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131530.11677'!
E1126 13:15:30.147719 11677 tera/monitor/teramo_main.cc:94] min: 1416935728579552 max: 1416978928579552

ERROR 2014-11-26 13:15:34,492 service 19462 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131532.11808'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131533.11808'!
E1126 13:15:33.666451 11808 tera/monitor/teramo_main.cc:94] min: 1416935732557680 max: 1416978932557680

ERROR 2014-11-26 13:15:40,093 service 19463 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131538.11883'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131539.11883'!
E1126 13:15:39.360563 11883 tera/monitor/teramo_main.cc:94] min: 1416935738224207 max: 1416978938224207

ERROR 2014-11-26 13:17:48,616 service 19463 139938049193696 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-131747.16210'!

ERROR 2014-11-26 13:25:18,197 service 3197 139780408006368 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132517.5018'!

ERROR 2014-11-26 13:25:20,834 service 3196 139780408006368 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132520.5077'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132520.5077'!
E1126 13:25:20.723865  5077 tera/monitor/teramo_main.cc:94] min: 1416936319735415 max: 1416979519735415

ERROR 2014-11-26 13:25:27,228 service 3197 139780408006368 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132525.5272'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132526.5272'!
E1126 13:25:26.991552  5272 tera/monitor/teramo_main.cc:94] min: 1416936325603993 max: 1416979525603993

ERROR 2014-11-26 13:25:54,909 service 5699 140606569457376 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132554.5781'!

ERROR 2014-11-26 13:26:02,254 service 5739 140606569457376 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132601.5918'!

ERROR 2014-11-26 13:26:06,283 service 5699 140606569457376 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132605.6060'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132606.6060'!
E1126 13:26:06.041172  6060 tera/monitor/teramo_main.cc:94] min: 1416936365052414 max: 1416979565052414

ERROR 2014-11-26 13:26:10,063 service 5699 140606569457376 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132609.6128'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132609.6128'!
E1126 13:26:09.842602  6128 tera/monitor/teramo_main.cc:94] min: 1416936368827896 max: 1416979568827896

ERROR 2014-11-26 13:26:13,254 service 5739 140606569457376 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132612.7542'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132613.7542'!
E1126 13:26:13.048487  7542 tera/monitor/teramo_main.cc:94] min: 1416936372034960 max: 1416979572034960

ERROR 2014-11-26 13:26:17,708 service 5699 140606569457376 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132616.7674'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132617.7674'!
E1126 13:26:17.286300  7674 tera/monitor/teramo_main.cc:94] min: 1416936375972291 max: 1416979575972291

ERROR 2014-11-26 13:26:21,677 service 5739 140606569457376 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132620.7739'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132621.7739'!
E1126 13:26:21.207756  7739 tera/monitor/teramo_main.cc:94] min: 1416936379974022 max: 1416979579974022

ERROR 2014-11-26 13:26:24,853 service 5739 140606569457376 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132623.7862'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132624.7862'!
E1126 13:26:24.630358  7862 tera/monitor/teramo_main.cc:94] min: 1416936383578494 max: 1416979583578494

ERROR 2014-11-26 13:26:29,413 service 5699 140606569457376 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132628.7935'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132629.7935'!
E1126 13:26:29.247216  7935 tera/monitor/teramo_main.cc:94] min: 1416936388238363 max: 1416979588238363

ERROR 2014-11-26 13:26:33,089 service 5699 140606569457376 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132632.8037'!

WARNING 2014-11-26 13:26:33,098 base 5699 140606569457376 Not Found: /img/favicon.ico
ERROR 2014-11-26 13:26:34,463 service 5699 140606569457376 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132633.8113'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132634.8113'!
E1126 13:26:34.179805  8113 tera/monitor/teramo_main.cc:94] min: 1416936393104967 max: 1416979593104967

ERROR 2014-11-26 13:26:36,910 service 5699 140606569457376 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132636.8172'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132636.8172'!
E1126 13:26:36.739809  8172 tera/monitor/teramo_main.cc:94] min: 1416936395753465 max: 1416979595753465

ERROR 2014-11-26 13:26:41,492 service 5739 140606569457376 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132640.8305'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132641.8305'!
E1126 13:26:41.322077  8305 tera/monitor/teramo_main.cc:94] min: 1416936400440365 max: 1416979600440365

ERROR 2014-11-26 13:27:07,387 service 5699 140606569457376 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132706.8792'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132707.8792'!
E1126 13:27:07.204284  8792 tera/monitor/teramo_main.cc:94] min: 1416967200000000 max: 1416981600000000

ERROR 2014-11-26 13:28:00,333 service 5739 140606569457376 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132759.10732'!

WARNING 2014-11-26 13:28:01,046 base 5739 140606569457376 Not Found: /img/favicon.ico
ERROR 2014-11-26 13:28:06,323 service 5739 140606569457376 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132805.10925'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132806.10925'!
E1126 13:28:06.190853 10925 tera/monitor/teramo_main.cc:94] min: 1416936485183369 max: 1416979685183369

ERROR 2014-11-26 13:28:06,617 service 5699 140606569457376 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132805.10936'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132806.10936'!
E1126 13:28:06.379402 10936 tera/monitor/teramo_main.cc:94] min: 1416936485354007 max: 1416979685354007

ERROR 2014-11-26 13:28:07,676 service 5739 140606569457376 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132806.11016'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132807.11016'!
E1126 13:28:07.498091 11016 tera/monitor/teramo_main.cc:94] min: 1416936486497718 max: 1416979686497718

WARNING 2014-11-26 13:28:07,866 base 5739 140606569457376 Not Found: /img/favicon.ico
ERROR 2014-11-26 13:28:07,890 service 5699 140606569457376 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132807.11027'!

WARNING 2014-11-26 13:28:07,959 base 5699 140606569457376 Not Found: /img/favicon.ico
WARNING 2014-11-26 13:28:07,983 base 5699 140606569457376 Not Found: /favicon.ico
ERROR 2014-11-26 13:28:09,266 service 5739 140606569457376 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132808.11097'!

ERROR 2014-11-26 13:28:12,677 service 5739 140606569457376 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132811.11535'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132812.11535'!
E1126 13:28:12.435441 11535 tera/monitor/teramo_main.cc:94] min: 1416936491441643 max: 1416979691441643

ERROR 2014-11-26 13:28:24,514 service 5699 140606569457376 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132823.12549'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132824.12549'!
E1126 13:28:24.305927 12549 tera/monitor/teramo_main.cc:94] min: 1416893220000000 max: 1416979620000000

ERROR 2014-11-26 13:28:52,646 service 5699 140606569457376 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132851.13129'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132852.13129'!
E1126 13:28:52.489089 13129 tera/monitor/teramo_main.cc:94] min: 1416893220000000 max: 1416979620000000

ERROR 2014-11-26 13:28:56,385 service 5739 140606569457376 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132854.13207'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132855.13207'!
E1126 13:28:55.842418 13207 tera/monitor/teramo_main.cc:94] min: 1416893220000000 max: 1416979620000000

ERROR 2014-11-26 13:28:56,875 service 5699 140606569457376 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132855.13258'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-132856.13258'!
E1126 13:28:56.645864 13258 tera/monitor/teramo_main.cc:94] min: 1416893220000000 max: 1416979620000000

WARNING 2014-11-26 13:32:06,354 base 5699 140606569457376 Not Found: /img/favicon.ico
ERROR 2014-11-26 13:32:08,998 service 5739 140606569457376 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-133206.20996'!

ERROR 2014-11-26 13:32:30,696 service 5699 140606569457376 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-133229.22451'!

ERROR 2014-11-26 13:32:36,060 service 5699 140606569457376 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-133234.22594'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-133235.22594'!
E1126 13:32:35.843109 22594 tera/monitor/teramo_main.cc:94] min: 1416891600000000 max: 1416978000000000

ERROR 2014-11-26 13:32:43,179 service 5739 140606569457376 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-133242.22783'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-133242.22783'!
E1126 13:32:42.956302 22783 tera/monitor/teramo_main.cc:94] min: 1416891600000000 max: 1416978000000000

ERROR 2014-11-26 13:32:46,216 service 5739 140606569457376 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-133245.22874'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-133246.22874'!
E1126 13:32:46.063513 22874 tera/monitor/teramo_main.cc:94] min: 1416891600000000 max: 1416978000000000

ERROR 2014-11-26 13:32:53,238 service 5699 140606569457376 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-133251.22992'!

ERROR 2014-11-26 13:32:55,760 service 5699 140606569457376 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-133255.23076'!

WARNING 2014-11-26 13:33:10,548 base 5699 140606569457376 Not Found: /img/favicon.ico
ERROR 2014-11-26 13:33:34,417 service 5739 140606569457376 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-133310.23605'!

ERROR 2014-11-26 13:44:37,016 service 19038 140708490548960 execute command error the input 
 db-stest-zk0.db01.baidu.com:3000/sandbox/tera/nmg-lb(
Traceback (most recent call last):
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/service.py", line 92, in _execute
    status, _ , error = self.shell_helper.run_with_retuncode(command)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/frame/shell/command.py", line 36, in run_with_retuncode
    output, errout = p.communicate()
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 754, in communicate
    return self._communicate(input)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 1312, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 1366, in _communicate_with_poll
    ready = poller.poll()
  File "/home/users/wangtaize/.jumbo/lib/python2.7/site-packages/gunicorn/workers/base.py", line 154, in handle_abort
    sys.exit(1)
SystemExit: 1
ERROR 2014-11-26 13:44:51,274 service 21151 140708490548960 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-134449.21271'!

ERROR 2014-11-26 13:45:24,014 service 21151 140708490548960 execute command error the input 
 db-stest-zk0.db01.baidu.com:3000/sandbox/tera/nmg-lb(
Traceback (most recent call last):
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/service.py", line 92, in _execute
    status, _ , error = self.shell_helper.run_with_retuncode(command)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/frame/shell/command.py", line 36, in run_with_retuncode
    output, errout = p.communicate()
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 754, in communicate
    return self._communicate(input)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 1312, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 1366, in _communicate_with_poll
    ready = poller.poll()
  File "/home/users/wangtaize/.jumbo/lib/python2.7/site-packages/gunicorn/workers/base.py", line 154, in handle_abort
    sys.exit(1)
SystemExit: 1
ERROR 2014-11-26 13:46:10,965 service 19037 140708490548960 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-134609.24540'!

ERROR 2014-11-26 13:46:14,079 base 19037 140708490548960 Internal Server Error: /monitor/statLine
Traceback (most recent call last):
  File "/home/users/wangtaize/.jumbo/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/decorator.py", line 24, in node_required_wrapper
    return func(request, *args, **kwds)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/views.py", line 83, in render_node_stat_line
    response = node_service.get_stat(zk,zk_path, node, start_time,end_time)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/service.py", line 61, in get_stat
    req.min_timestamp = long(t_start)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 471, in field_setter
    self._fields[field] = type_checker.CheckValue(new_value)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/site-packages/google/protobuf/internal/type_checkers.py", line 119, in CheckValue
    raise ValueError('Value out of range: %d' % proposed_value)
ValueError: Value out of range: 1416937574079007031296
ERROR 2014-11-26 13:46:16,012 service 23982 140708490548960 execute command error the input 
 db-stest-zk0.db01.baidu.com:3000/sandbox/tera/nmg-lb(
Traceback (most recent call last):
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/service.py", line 92, in _execute
    status, _ , error = self.shell_helper.run_with_retuncode(command)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/frame/shell/command.py", line 36, in run_with_retuncode
    output, errout = p.communicate()
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 754, in communicate
    return self._communicate(input)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 1312, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 1366, in _communicate_with_poll
    ready = poller.poll()
  File "/home/users/wangtaize/.jumbo/lib/python2.7/site-packages/gunicorn/workers/base.py", line 154, in handle_abort
    sys.exit(1)
SystemExit: 1
ERROR 2014-11-26 13:46:24,142 service 25879 140708490548960 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-134623.25968'!

ERROR 2014-11-26 13:46:25,041 base 25879 140708490548960 Internal Server Error: /monitor/statLine
Traceback (most recent call last):
  File "/home/users/wangtaize/.jumbo/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/decorator.py", line 24, in node_required_wrapper
    return func(request, *args, **kwds)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/views.py", line 83, in render_node_stat_line
    response = node_service.get_stat(zk,zk_path, node, start_time,end_time)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/service.py", line 61, in get_stat
    req.min_timestamp = long(t_start)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 471, in field_setter
    self._fields[field] = type_checker.CheckValue(new_value)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/site-packages/google/protobuf/internal/type_checkers.py", line 119, in CheckValue
    raise ValueError('Value out of range: %d' % proposed_value)
ValueError: Value out of range: 1416937585041577869312
ERROR 2014-11-26 13:46:37,215 base 25879 140708490548960 Internal Server Error: /monitor/statLine
Traceback (most recent call last):
  File "/home/users/wangtaize/.jumbo/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/decorator.py", line 24, in node_required_wrapper
    return func(request, *args, **kwds)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/views.py", line 83, in render_node_stat_line
    response = node_service.get_stat(zk,zk_path, node, start_time,end_time)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/service.py", line 61, in get_stat
    req.min_timestamp = long(t_start)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 471, in field_setter
    self._fields[field] = type_checker.CheckValue(new_value)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/site-packages/google/protobuf/internal/type_checkers.py", line 119, in CheckValue
    raise ValueError('Value out of range: %d' % proposed_value)
ValueError: Value out of range: 1416937597215796101120
ERROR 2014-11-26 13:46:48,023 base 25879 140708490548960 Internal Server Error: /monitor/statLine
Traceback (most recent call last):
  File "/home/users/wangtaize/.jumbo/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/decorator.py", line 24, in node_required_wrapper
    return func(request, *args, **kwds)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/views.py", line 83, in render_node_stat_line
    response = node_service.get_stat(zk,zk_path, node, start_time,end_time)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/service.py", line 61, in get_stat
    req.min_timestamp = long(t_start)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 471, in field_setter
    self._fields[field] = type_checker.CheckValue(new_value)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/site-packages/google/protobuf/internal/type_checkers.py", line 119, in CheckValue
    raise ValueError('Value out of range: %d' % proposed_value)
ValueError: Value out of range: 1416937608023194992640
ERROR 2014-11-26 13:46:50,029 service 19037 140708490548960 execute command error the input 
 db-stest-zk0.db01.baidu.com:3000/sandbox/tera/nmg-lb(
Traceback (most recent call last):
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/service.py", line 92, in _execute
    status, _ , error = self.shell_helper.run_with_retuncode(command)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/frame/shell/command.py", line 36, in run_with_retuncode
    output, errout = p.communicate()
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 754, in communicate
    return self._communicate(input)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 1312, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 1366, in _communicate_with_poll
    ready = poller.poll()
  File "/home/users/wangtaize/.jumbo/lib/python2.7/site-packages/gunicorn/workers/base.py", line 154, in handle_abort
    sys.exit(1)
SystemExit: 1
ERROR 2014-11-26 13:48:48,154 service 30690 140037164472032 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-134846.30756'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-134847.30756'!
E1126 13:48:47.386910 30756 tera/monitor/teramo_main.cc:94] min: 1416937725856093 max: 1416980925856093

ERROR 2014-11-26 13:49:02,604 service 30690 140037164472032 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-134901.31119'!

ERROR 2014-11-26 13:49:05,882 service 30690 140037164472032 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-134903.31219'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-134904.31219'!
E1126 13:49:04.636199 31219 tera/monitor/teramo_main.cc:94] min: 1416937743473348 max: 1416980943473348

ERROR 2014-11-26 13:49:10,586 service 30690 140037164472032 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-134908.31308'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-134909.31308'!
E1126 13:49:09.771028 31308 tera/monitor/teramo_main.cc:94] min: 1416937748439687 max: 1416980948439687

ERROR 2014-11-26 13:49:14,217 service 30690 140037164472032 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-134912.32195'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-134912.32195'!
E1126 13:49:12.996754 32195 tera/monitor/teramo_main.cc:94] min: 1416937751813825 max: 1416980951813825

ERROR 2014-11-26 13:49:17,675 service 30690 140037164472032 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-134916.32627'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-134916.32627'!
E1126 13:49:16.902042 32627 tera/monitor/teramo_main.cc:94] min: 1416937755717226 max: 1416980955717226

ERROR 2014-11-26 13:49:21,007 service 30690 140037164472032 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-134919.32692'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-134920.32692'!
E1126 13:49:20.199237 32692 tera/monitor/teramo_main.cc:94] min: 1416937759062761 max: 1416980959062761

ERROR 2014-11-26 13:49:26,023 service 30690 140037164472032 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-134923.327'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-134924.327'!
E1126 13:49:24.395414   327 tera/monitor/teramo_main.cc:94] min: 1416937762781286 max: 1416980962781286

ERROR 2014-11-26 13:49:28,017 service 30689 140037164472032 execute command error the input 
 db-stest-zk0.db01.baidu.com:3000/sandbox/tera/nmg-lb(
Traceback (most recent call last):
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/monitor/service.py", line 88, in _execute
    status, _ , error = self.shell_helper.run_with_retuncode(command)
  File "/home/users/wangtaize/workspace/ps/se/tera/tera/monitor/http/src/frame/shell/command.py", line 36, in run_with_retuncode
    output, errout = p.communicate()
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 754, in communicate
    return self._communicate(input)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 1312, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/home/users/wangtaize/.jumbo/lib/python2.7/subprocess.py", line 1366, in _communicate_with_poll
    ready = poller.poll()
  File "/home/users/wangtaize/.jumbo/lib/python2.7/site-packages/gunicorn/workers/base.py", line 154, in handle_abort
    sys.exit(1)
SystemExit: 1
ERROR 2014-11-26 13:49:29,204 service 30690 140037164472032 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-134927.419'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-134928.419'!
E1126 13:49:28.424674   419 tera/monitor/teramo_main.cc:94] min: 1416937767325322 max: 1416980967325322

ERROR 2014-11-26 13:49:33,226 service 30690 140037164472032 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-134931.566'!

ERROR 2014-11-26 13:49:36,637 service 569 140037164472032 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-134934.646'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-134935.646'!
E1126 13:49:35.569835   646 tera/monitor/teramo_main.cc:94] min: 1416937774302291 max: 1416980974302291

ERROR 2014-11-26 13:50:27,640 service 30690 140037164472032 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-135026.3443'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-135026.3443'!
E1126 13:50:26.935925  3443 tera/monitor/teramo_main.cc:94] min: 1416937825833912 max: 1416981025833912

ERROR 2014-11-26 13:50:55,410 service 569 140037164472032 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-135053.3900'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-135054.3900'!
E1126 13:50:54.620308  3900 tera/monitor/teramo_main.cc:94] min: 1416937852922142 max: 1416981052922142

ERROR 2014-11-26 13:50:58,577 service 30690 140037164472032 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-135056.3990'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-135057.3990'!
E1126 13:50:57.776803  3990 tera/monitor/teramo_main.cc:94] min: 1416937856614705 max: 1416981056614705

ERROR 2014-11-26 13:51:02,615 service 569 140037164472032 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-135100.4118'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-135101.4118'!
E1126 13:51:01.814952  4118 tera/monitor/teramo_main.cc:94] min: 1416937860169505 max: 1416981060169505

ERROR 2014-11-26 13:51:51,619 service 569 140037164472032 Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-135150.9807'!
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20141126-135150.9807'!
E1126 13:51:50.866395  9807 tera/monitor/teramo_main.cc:94] min: 1416937909752745 max: 1416981109752745

ERROR 2014-11-30 22:04:09,613 service 4111 4380041216 None
ERROR 2014-11-30 22:04:09,614 service 4111 4380041216 fail to execute command ['/home/users/wangtaize/workspace/ps/se/tera/teramo', '/var/folders/6t/bxgtws6s57x6thn8nzrkbn4m0000gn/T/tmp9mabtb', '/var/folders/6t/bxgtws6s57x6thn8nzrkbn4m0000gn/T/tmpvFzBMN'] ,error None
ERROR 2014-11-30 22:04:09,614 base 4111 4380041216 Internal Server Error: /monitor/getNodeList
Traceback (most recent call last):
  File "/Users/wangtaize/local/eagle-env/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/wangtaize/workspace/tera/tera/monitor/http/src/monitor/views.py", line 108, in get_node_list
    return response_builder.error("no data")\
  File "/Users/wangtaize/workspace/tera/tera/monitor/http/src/frame/net/http.py", line 258, in build_json
    return self.build()
  File "/Users/wangtaize/workspace/tera/tera/monitor/http/src/frame/net/http.py", line 300, in build
    mimetype=self.mimetype)
  File "/Users/wangtaize/local/eagle-env/lib/python2.7/site-packages/django/http/response.py", line 318, in __init__
    super(HttpResponse, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'mimetype'
ERROR 2014-11-30 22:04:46,373 service 4111 4380041216 None
ERROR 2014-11-30 22:04:46,373 service 4111 4380041216 fail to execute command ['/home/users/wangtaize/workspace/ps/se/tera/teramo', '/var/folders/6t/bxgtws6s57x6thn8nzrkbn4m0000gn/T/tmpE7aZyI', '/var/folders/6t/bxgtws6s57x6thn8nzrkbn4m0000gn/T/tmp1ymZ4v'] ,error None
ERROR 2014-11-30 22:04:46,373 base 4111 4380041216 Internal Server Error: /monitor/getNodeList
Traceback (most recent call last):
  File "/Users/wangtaize/local/eagle-env/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/wangtaize/workspace/tera/tera/monitor/http/src/monitor/views.py", line 108, in get_node_list
    return response_builder.error("no data")\
  File "/Users/wangtaize/workspace/tera/tera/monitor/http/src/frame/net/http.py", line 258, in build_json
    return self.build()
  File "/Users/wangtaize/workspace/tera/tera/monitor/http/src/frame/net/http.py", line 300, in build
    mimetype=self.mimetype)
  File "/Users/wangtaize/local/eagle-env/lib/python2.7/site-packages/django/http/response.py", line 318, in __init__
    super(HttpResponse, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'mimetype'
ERROR 2014-11-30 22:04:47,850 service 4111 4380041216 None
ERROR 2014-11-30 22:04:47,850 service 4111 4380041216 fail to execute command ['/home/users/wangtaize/workspace/ps/se/tera/teramo', '/var/folders/6t/bxgtws6s57x6thn8nzrkbn4m0000gn/T/tmpJsGYty', '/var/folders/6t/bxgtws6s57x6thn8nzrkbn4m0000gn/T/tmpS_gi4B'] ,error None
ERROR 2014-11-30 22:04:47,851 base 4111 4380041216 Internal Server Error: /monitor/getNodeList
Traceback (most recent call last):
  File "/Users/wangtaize/local/eagle-env/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/wangtaize/workspace/tera/tera/monitor/http/src/monitor/views.py", line 108, in get_node_list
    return response_builder.error("no data")\
  File "/Users/wangtaize/workspace/tera/tera/monitor/http/src/frame/net/http.py", line 258, in build_json
    return self.build()
  File "/Users/wangtaize/workspace/tera/tera/monitor/http/src/frame/net/http.py", line 300, in build
    mimetype=self.mimetype)
  File "/Users/wangtaize/local/eagle-env/lib/python2.7/site-packages/django/http/response.py", line 318, in __init__
    super(HttpResponse, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'mimetype'
ERROR 2014-11-30 22:04:50,568 service 4111 4380041216 None
ERROR 2014-11-30 22:04:50,568 service 4111 4380041216 fail to execute command ['/home/users/wangtaize/workspace/ps/se/tera/teramo', '/var/folders/6t/bxgtws6s57x6thn8nzrkbn4m0000gn/T/tmpdI6FEb', '/var/folders/6t/bxgtws6s57x6thn8nzrkbn4m0000gn/T/tmptbUaMl'] ,error None
ERROR 2014-11-30 22:04:50,569 base 4111 4380041216 Internal Server Error: /monitor/getNodeList
Traceback (most recent call last):
  File "/Users/wangtaize/local/eagle-env/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/wangtaize/workspace/tera/tera/monitor/http/src/monitor/views.py", line 108, in get_node_list
    return response_builder.error("no data")\
  File "/Users/wangtaize/workspace/tera/tera/monitor/http/src/frame/net/http.py", line 258, in build_json
    return self.build()
  File "/Users/wangtaize/workspace/tera/tera/monitor/http/src/frame/net/http.py", line 300, in build
    mimetype=self.mimetype)
  File "/Users/wangtaize/local/eagle-env/lib/python2.7/site-packages/django/http/response.py", line 318, in __init__
    super(HttpResponse, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'mimetype'
ERROR 2014-11-30 22:04:52,487 service 4111 4380041216 None
ERROR 2014-11-30 22:04:52,487 service 4111 4380041216 fail to execute command ['/home/users/wangtaize/workspace/ps/se/tera/teramo', '/var/folders/6t/bxgtws6s57x6thn8nzrkbn4m0000gn/T/tmpjqhMBQ', '/var/folders/6t/bxgtws6s57x6thn8nzrkbn4m0000gn/T/tmpNqsMg6'] ,error None
ERROR 2014-11-30 22:04:52,488 base 4111 4380041216 Internal Server Error: /monitor/getNodeList
Traceback (most recent call last):
  File "/Users/wangtaize/local/eagle-env/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/wangtaize/workspace/tera/tera/monitor/http/src/monitor/views.py", line 108, in get_node_list
    return response_builder.error("no data")\
  File "/Users/wangtaize/workspace/tera/tera/monitor/http/src/frame/net/http.py", line 258, in build_json
    return self.build()
  File "/Users/wangtaize/workspace/tera/tera/monitor/http/src/frame/net/http.py", line 300, in build
    mimetype=self.mimetype)
  File "/Users/wangtaize/local/eagle-env/lib/python2.7/site-packages/django/http/response.py", line 318, in __init__
    super(HttpResponse, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'mimetype'
ERROR 2014-11-30 22:06:50,855 service 4111 4380041216 None
ERROR 2014-11-30 22:06:50,855 service 4111 4380041216 fail to execute command ['/home/users/wangtaize/workspace/ps/se/tera/teramo', '/var/folders/6t/bxgtws6s57x6thn8nzrkbn4m0000gn/T/tmpkVJXtH', '/var/folders/6t/bxgtws6s57x6thn8nzrkbn4m0000gn/T/tmpGanjgU'] ,error None
ERROR 2014-11-30 22:06:50,855 base 4111 4380041216 Internal Server Error: /monitor/getNodeList
Traceback (most recent call last):
  File "/Users/wangtaize/local/eagle-env/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/wangtaize/workspace/tera/tera/monitor/http/src/monitor/views.py", line 108, in get_node_list
    return response_builder.error("no data")\
  File "/Users/wangtaize/workspace/tera/tera/monitor/http/src/frame/net/http.py", line 258, in build_json
    return self.build()
  File "/Users/wangtaize/workspace/tera/tera/monitor/http/src/frame/net/http.py", line 300, in build
    mimetype=self.mimetype)
  File "/Users/wangtaize/local/eagle-env/lib/python2.7/site-packages/django/http/response.py", line 318, in __init__
    super(HttpResponse, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'mimetype'
ERROR 2014-11-30 22:08:14,888 service 4111 4380041216 None
ERROR 2014-11-30 22:08:14,888 service 4111 4380041216 fail to execute command ['/home/users/wangtaize/workspace/ps/se/tera/teramo', '/var/folders/6t/bxgtws6s57x6thn8nzrkbn4m0000gn/T/tmpx5Qeim', '/var/folders/6t/bxgtws6s57x6thn8nzrkbn4m0000gn/T/tmp1KbQHp'] ,error None
ERROR 2014-11-30 22:08:14,888 base 4111 4380041216 Internal Server Error: /monitor/getNodeList
Traceback (most recent call last):
  File "/Users/wangtaize/local/eagle-env/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/wangtaize/workspace/tera/tera/monitor/http/src/monitor/views.py", line 108, in get_node_list
    return response_builder.error("no data")\
  File "/Users/wangtaize/workspace/tera/tera/monitor/http/src/frame/net/http.py", line 258, in build_json
    return self.build()
  File "/Users/wangtaize/workspace/tera/tera/monitor/http/src/frame/net/http.py", line 300, in build
    mimetype=self.mimetype)
  File "/Users/wangtaize/local/eagle-env/lib/python2.7/site-packages/django/http/response.py", line 318, in __init__
    super(HttpResponse, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'mimetype'
ERROR 2014-11-30 22:08:36,565 service 4111 4380041216 None
ERROR 2014-11-30 22:08:36,566 service 4111 4380041216 fail to execute command ['/home/users/wangtaize/workspace/ps/se/tera/teramo', '/var/folders/6t/bxgtws6s57x6thn8nzrkbn4m0000gn/T/tmphcr0Xj', '/var/folders/6t/bxgtws6s57x6thn8nzrkbn4m0000gn/T/tmpdjYx4i'] ,error None
ERROR 2014-11-30 22:08:36,566 base 4111 4380041216 Internal Server Error: /monitor/getNodeList
Traceback (most recent call last):
  File "/Users/wangtaize/local/eagle-env/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/wangtaize/workspace/tera/tera/monitor/http/src/monitor/views.py", line 108, in get_node_list
    return response_builder.error("no data")\
  File "/Users/wangtaize/workspace/tera/tera/monitor/http/src/frame/net/http.py", line 258, in build_json
    return self.build()
  File "/Users/wangtaize/workspace/tera/tera/monitor/http/src/frame/net/http.py", line 300, in build
    mimetype=self.mimetype)
  File "/Users/wangtaize/local/eagle-env/lib/python2.7/site-packages/django/http/response.py", line 318, in __init__
    super(HttpResponse, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'mimetype'
